module.exports = {
  boolean: require('./boolean'),
  css: require('./css'),
  haml: require('./haml'),
  handlebars: require('./handlebars'),
  ini: require('./ini'),
  jade: require('./jade'),
  json: require('./json'),
  less: require('./less'),
  markdown: require('./markdown'),
  number: require('./number'),
  password: require('./password'),
  pick: require('./pick'),
  sql: require('./sql'),
  string: require('./string'),
  svg: require('./svg'),
  text: require('./text'),
  textile: require('./textile'),
  xml: require('./xml'),
  yaml: require('./yaml')
}